package watten.tests;

import watten.CONSTANTS;
import watten.Card;

public class CardDeck {
	
	public Card hA, hK, hO, hU, h10, h9, h8, h7;
	public Card sA, sK, sO, sU, s10, s9, s8, s7, s6;
	public Card eA, eK, eO, eU, e10, e9, e8, e7;
	public Card lA, lK, lO, lU, l10, l9, l8, l7;

	public CardDeck() {
		hA = new Card(CONSTANTS.HERZ, CONSTANTS.AS);
		hK = new Card(CONSTANTS.HERZ, CONSTANTS.KOENIG);
		hO = new Card(CONSTANTS.HERZ, CONSTANTS.OBER);
		hU = new Card(CONSTANTS.HERZ, CONSTANTS.UNTER);
		h10 = new Card(CONSTANTS.HERZ, CONSTANTS.ZEHNER);
		h9 = new Card(CONSTANTS.HERZ, CONSTANTS.NEUNER);
		h8 = new Card(CONSTANTS.HERZ, CONSTANTS.ACHTER);
		h7 = new Card(CONSTANTS.HERZ, CONSTANTS.SIEBNER);
		
		sA = new Card(CONSTANTS.SCHELL, CONSTANTS.AS);
		sK = new Card(CONSTANTS.SCHELL, CONSTANTS.KOENIG);
		sO = new Card(CONSTANTS.SCHELL, CONSTANTS.OBER);
		sU = new Card(CONSTANTS.SCHELL, CONSTANTS.UNTER);
		s10 = new Card(CONSTANTS.SCHELL, CONSTANTS.ZEHNER);
		s9 = new Card(CONSTANTS.SCHELL, CONSTANTS.NEUNER);
		s8 = new Card(CONSTANTS.SCHELL, CONSTANTS.ACHTER);
		s7 = new Card(CONSTANTS.SCHELL, CONSTANTS.SIEBNER);
		s6 = new Card(CONSTANTS.SCHELL, CONSTANTS.SECHSER);

		eA = new Card(CONSTANTS.EICHEL, CONSTANTS.AS);
		eK = new Card(CONSTANTS.EICHEL, CONSTANTS.KOENIG);
		eO = new Card(CONSTANTS.EICHEL, CONSTANTS.OBER);
		eU = new Card(CONSTANTS.EICHEL, CONSTANTS.UNTER);
		e10 = new Card(CONSTANTS.EICHEL, CONSTANTS.ZEHNER);
		e9 = new Card(CONSTANTS.EICHEL, CONSTANTS.NEUNER);
		e8 = new Card(CONSTANTS.EICHEL, CONSTANTS.ACHTER);
		e7 = new Card(CONSTANTS.EICHEL, CONSTANTS.SIEBNER);

		lA = new Card(CONSTANTS.LAUB, CONSTANTS.AS);
		lK = new Card(CONSTANTS.LAUB, CONSTANTS.KOENIG);
		lO = new Card(CONSTANTS.LAUB, CONSTANTS.OBER);
		lU = new Card(CONSTANTS.LAUB, CONSTANTS.UNTER);
		l10 = new Card(CONSTANTS.LAUB, CONSTANTS.ZEHNER);
		l9 = new Card(CONSTANTS.LAUB, CONSTANTS.NEUNER);
		l8 = new Card(CONSTANTS.LAUB, CONSTANTS.ACHTER);
		l7 = new Card(CONSTANTS.LAUB, CONSTANTS.SIEBNER);
	}
}
